In [2]:
import numpy as np
# rows are the number of students and columns determines the marks in each subject of a student.
marks=np.array([
    [85,90,78,94],
    [76,88,82,79],
    [91,88,81,84],
    [68,74,69,70],
    [88,89,79,96]
])
print("Marks Array:\n", marks)
print("Shape:",marks.shape)

Marks Array:
 [[85 90 78 94]
 [76 88 82 79]
 [91 88 81 84]
 [68 74 69 70]
 [88 89 79 96]]
Shape: (5, 4)


In [3]:
# calculating average,total,max ,min per student
max_per_student=marks.max(axis=1)
average_per_student=marks.mean(axis=1)
min_per_student=marks.min(axis=1)
total_per_student=marks.sum(axis=1)
print("Total marks per student:",total_per_student)
print("Average marks per student:",average_per_student)
print("Maximum marks per student:",max_per_student)
print("Minimum marks per student:",min_per_student)


Total marks per student: [347 325 344 281 352]
Average marks per student: [86.75 81.25 86.   70.25 88.  ]
Maximum marks per student: [94 88 91 74 96]
Minimum marks per student: [78 76 81 68 79]


In [5]:
# Checking pass or fail logic
subject_pass= marks>=40
all_subjects_pass=np.all(subject_pass,axis=1)
#print(subject_pass)
#print(all_subjects_pass)
avg_marks=np.mean(marks,axis=1)
avg_pass=avg_marks>=50
final_pass=all_subjects_pass & avg_pass
#print(final_pass)
for i in range (len(final_pass)):
    status="Pass" if final_pass[i] else "fail"
    print(f"Student {i+1}:{status}")


[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[ True  True  True  True  True]
Student 1:Pass
Student 2:Pass
Student 3:Pass
Student 4:Pass
Student 5:Pass


In [18]:
# Grade Assignment to the student
averages=np.mean(marks,axis=1)
grades=np.empty_like(averages,dtype='U1') # creates the empty array with the same shape as averages.
#print(grades)
grades[averages>=90]='A'
grades[(averages >= 80) & (averages < 90)] = 'B'
grades[(averages >= 70) & (averages < 80)] = 'C'
grades[(averages >= 60) & (averages < 70)] = 'D'
grades[averages < 60] = 'F'
#print(grades)
for i in range(len(grades)):
    print(f"Student {i+1} | Average:{averages[i]} | Grade:{grades[i]}")
    


['' '' '' '' '']
['B' 'B' 'B' 'C' 'B']
Student 1 | Average:86.75 | Grade:B
Student 2 | Average:81.25 | Grade:B
Student 3 | Average:86.0 | Grade:B
Student 4 | Average:70.25 | Grade:C
Student 5 | Average:88.0 | Grade:B


In [8]:
# highest and lowest according to the subjects
highest_sub=marks.max(axis=0)
lowest_sub=marks.min(axis=0)
print("Highest in each subject:",highest_sub)
print("Lowest in each subject:",lowest_sub)
for i in range(marks.shape[1]):
    print(f"Subject{i+1}:Highest:{highest_sub[i]},Lowest:{lowest_sub[i]}")

Highest in each subject: [91 90 82 96]
Lowest in each subject: [68 74 69 70]
Subject1:Highest:91,Lowest:68
Subject2:Highest:90,Lowest:74
Subject3:Highest:82,Lowest:69
Subject4:Highest:96,Lowest:70


In [25]:
# Ranking students based on total marks
totals=np.sum(marks,axis=1)
print(totals)
sort_total=-np.sort(-totals)
sort_indices=np.argsort(-totals)
print(sort_total)
print(sort_indices)
for i in range(len(sort_total)):
    print(f"Rank:{i+1}:Student {sort_indices[i]+1} with total:{sort_total[i]}")

[347 325 344 281 352]
[352 347 344 325 281]
[4 0 2 1 3]
Rank:1:Student 5 with total:352
Rank:2:Student 1 with total:347
Rank:3:Student 3 with total:344
Rank:4:Student 2 with total:325
Rank:5:Student 4 with total:281
