In [2]:
#indexing
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[-1])
print(arr[-3])
print(arr[-5])

10
30
50
30
10


In [6]:
#slicing
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[2:5:2])
print(arr[::-1])

[30 50]
[50 40 30 20 10]


In [9]:
# facny indexing
import numpy as np 
arr=np.array([10,20,30,40,50,60])
print(arr[[0,2,4]])


[10 30 50]


In [10]:
# filtering(Boolean Masking)
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [12]:
# Boolean Indexing/filtering
import numpy as np
arr=np.array([10,20,30,40,50])
mask=arr>25
print(mask)

filtered_array=arr[mask]
print(filtered_array)


[False False  True  True  True]
[30 40 50]
