In [2]:
# spliting the array horizontally. Rule: number of columns must be divisible by spliting value that is 3 in this case and divides array into 3 parts.
import numpy as np
arr=np.array([1,2,3,4,5,6])
split=np.hsplit(arr,3)
split

[array([1, 2]), array([3, 4]), array([5, 6])]

In [3]:
# vertical spliting of the array> Number of rows must be divisible by spliting value that is 2 here and it divides array into 2 parts.
arr=np.array([[1,2],[3,4],[5,6],[7,8]])
np.vsplit(arr,2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [6]:
x=np.arange(1,25).reshape(2,12)
print(x)
np.hsplit(x,(4,5))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5],
        [17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

In [11]:
#slicing in matrices.
arr=np.array([[1,2],[3,4],[5,6]])
print(arr[1:3])
print(arr[0:2,0])
print(arr[:,0:2])


[[3 4]
 [5 6]]
[1 3]
[[1 2]
 [3 4]
 [5 6]]


In [18]:
# max,mins in matrices
data=np.array([[1,2],[3,4],[5,6]])
print(data.max())
print(data.min())
print(data.min(axis=0))
print(data.min(axis=1))
print(data.min(axis=0))
print(data.max(axis=0))
print(data.max(axis=1))
print(data.sum(axis=0))
print(data.sum(axis=1))
print(data.sum())


6
1
[1 2]
[1 3 5]
[1 2]
[5 6]
[2 4 6]
[ 9 12]
[ 3  7 11]
21


In [22]:
# unique() in Numpy. It removes the duplicate elements and prints the array in sorted form.
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique,counts,indices=np.unique(a,return_counts=True,return_index=True)
print(unique)
print(counts) # counts how many times the element appeared in the array.
print(indices) # it returns the indices of first occurences of the unique value at the array.

[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]
[3 2 2 2 1 1 1 1 1 1]


In [28]:
# unique in matrices
a_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,2,3,4]])
unique=np.unique(a_2d)
print(unique)
unique_rows=np.unique(a_2d,axis=0) # to print the unique rows axis must be specified.
print(unique_rows)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
#transpose of the matrix
arr=np.arange(6).reshape((2,3))
print(arr)
arr.transpose()  # or arr.T

[[0 1 2]
 [3 4 5]]


array([[0, 3],
       [1, 4],
       [2, 5]])

In [44]:
# flip in 2D array
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
flip_both_axis=np.flip(arr)
print(flip_both_axis)
flip_row=np.flip(arr,axis=0)
print(flip_row)
flip_col=np.flip(arr,axis=1)
print(flip_col)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [48]:
# specific row and column flip
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a[1]=np.flip(a[1]) # the row 1 of the array gets reversed.
print(a)
a[:,1]=np.flip(a[:,1])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [6 5 4]
 [7 8 9]]
[[1 8 3]
 [6 5 4]
 [7 2 9]]


In [53]:
# use of flatten in numpy
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a1=x.flatten()
a1[0]=99
print(x) # here orignal array remains safe.
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [54]:
# use of ravel in numpy
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a1=x.ravel()
a1[0]=99
print(x) # here orignal array changes.
print(a1)

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]
