In [1]:

python_list=[1,2,3,4,5]
print(python_list)
import numpy as np
numpy_array=np.array([1,2,3,4,5])
print(numpy_array)


[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [3]:
import numpy as np
#cannot leave zeros() empty as it determines the size of array.
arr=np.zeros()
arr

TypeError: zeros() missing required argument 'shape' (pos 0)

In [10]:
import numpy as np

# Zeros function in numpy
# it gives single zero only as floating value.
arr=np.zeros(3)
#it gives the 2D matrix with 3 rows and 2 columns
arr1=np.zeros((3,2))
# it gives 2D matrix as 2 rows and 3 columns as integer datatypes
arr2=np.zeros((2,3),dtype=int)
print(f"Arr:{arr}")
print(f"Arr1:{arr1}")
print(f"Arr2:{arr2}")

Arr:[0. 0. 0.]
Arr1:[[0. 0.]
 [0. 0.]
 [0. 0.]]
Arr2:[[0 0 0]
 [0 0 0]]


In [11]:
# ones function in numpy. It is all similar to the zeros function only difference is it prints 1 instead of 0.
import numpy as np
arr1=np.ones((2,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# full method in numpy.
import numpy as np
a=np.full((2,3),99.9)
a

array([[99.9, 99.9, 99.9],
       [99.9, 99.9, 99.9]])

In [15]:
# range method in nnumpy
import numpy as np
a= np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [19]:
#identity matrix 
import numpy as np
a=np.eye(3)
a1=np.eye(4,3)
a2=np.eye(5,5,2)
print(a)
print("\n")
print(a1)
print("\n")
print(a2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
#.shape It gives the dimension of array.
import numpy as np
arr=np.array([[1,2,3,4],
              [3,5,6,3]])
print(arr.shape)

(2, 4)


In [ ]:
# .size It gives the total number of elements present in array.
import numpy as np
arr=np.array([[1,2,3,4],
              [3,5,6,3]])
print(arr.size)


8
2


In [24]:
# .ndim It gives the totoal number of dimensions in array.
import numpy as np
arr=np.array([[1,2,3,4],
              [3,5,6,3]])
print(arr.ndim)

2


In [26]:
# .dtype It is used to identify the datatypes of an element in a datatype.
import numpy as np
arr=np.array([[123,2,3,4],
              [3,5,6,3]])
print(arr.dtype)

int32


In [30]:
# .astype() It is used to change the datatypes of element of an array.
import numpy as np
arr=np.array([[1,2,3,4],
              [3,5,6,3]])
new_arr=arr.astype(str)
print(new_arr)
new_arr.dtype

[['1' '2' '3' '4']
 ['3' '5' '6' '3']]


dtype('<U11')